#ifndef GAME2D_ATORES_H
#define GAME2D_ATORES_H

#include <c2d2/chien2d2mapa.h>
#include <c2d2/ator.h>

enum { PLAYER, INIMIGO1, INIMIGO2, BOSS1, BOSS2 };
enum { MARCA_INIMIGO1 = C2D2M_PROG, MARCA_INIMIGO2, MARCA_BOSS1, MARCA_BOSS2, MARCA_MOEDA, MARCA_VIDA, MARCA_CAIXA_MOEDA, MARCA_SWITCH, MARCA_MOLA };
enum { EVT_MOEDA = EVT_JOGO_PROG, EVT_VIDA, EVT_DANO, EVT_ESCADA, EVT_MOLA };

#endif
